---
- name: Post-register baseline (ISO-aware, IP-based)
  hosts: all              # IMPORTANT: do NOT limit here; we filter by IP inside
  gather_facts: yes

  vars:
    satellite_url: "https://satellite.lab.example.com"
    satellite_api_user: "admin"        # dummy username - change to real user
    satellite_api_password: "redhat"   # dummy password - change to real password or use a token

  tasks:
    - name: Show basic context as we see it from AAP
      debug:
        msg:
          inventory_hostname: "{{ inventory_hostname }}"
          ansible_ip: "{{ ansible_default_ipv4.address | default('UNKNOWN') }}"
          target_ip: "{{ target_ip | default('UNDEFINED') }}"
          target_name: "{{ target_name | default('UNDEFINED') }}"

    # 1) Only the host whose IP == target_ip will continue;
    #    all others end their execution here.
    - name: Stop on all hosts except the one that just registered
      meta: end_host
      when: ansible_default_ipv4.address | default('') != target_ip | default('')

    # From this point on, ONLY the matching host runs the tasks below.

    # 2) Look up the Satellite host by IP (authoritative mapping)
    - name: Lookup Satellite host by IP
      uri:
        url: "{{ satellite_url }}/api/v2/hosts?search=ip={{ target_ip }}"
        method: GET
        user: "{{ satellite_api_user }}"
        password: "{{ satellite_api_password }}"
        force_basic_auth: yes
        validate_certs: no          # set to yes if CA trust is configured
        return_content: yes
      register: lookup_by_ip

    - name: Extract Satellite FQDN from lookup
      set_fact:
        sat_host_fqdn: >-
          {{
            lookup_by_ip.json.results[0].name
            | default('')
          }}

    - name: Fail clearly if Satellite could not find the host by IP
      fail:
        msg: "Could not find Satellite host for IP {{ target_ip }} in /api/v2/hosts"
      when: sat_host_fqdn == ''

    - name: Show Satellite host FQDN we will use
      debug:
        msg:
          sat_host_fqdn: "{{ sat_host_fqdn }}"

    # 3) Query host details from Satellite using the FQDN from the lookup
    - name: Query Satellite API for host details
      uri:
        url: "{{ satellite_url }}/api/v2/hosts/{{ sat_host_fqdn }}"
        method: GET
        user: "{{ satellite_api_user }}"
        password: "{{ satellite_api_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: sat_host

    # 4) Pull provision_source from host parameters
    - name: Extract provision_source from host parameters
      set_fact:
        provision_source: >-
          {{
            (sat_host.json.all_parameters | default([]))
            | selectattr('name', 'eq', 'provision_source')
            | map(attribute='value')
            | first
            | default('')
          }}

    - name: Show provision_source value as seen from Satellite API
      debug:
        msg:
          provision_source: "{{ provision_source | default('UNDEFINED') }}"

    # 5) Skip baseline if not an ISO host
    - name: Skip everything if this is not an ISO host
      meta: end_host
      when: provision_source | default('') != 'iso'

    # 6) Baseline actions actually executed only on ISO hosts
    - name: Inform that ISO baseline WILL run on this host
      debug:
        msg: "ISO baseline WILL run on {{ inventory_hostname }} (IP={{ ansible_default_ipv4.address }}, provision_source={{ provision_source }})"

    - name: Touch marker file to prove baseline ran
      file:
        path: /root/iso_baseline_ran
        state: touch

    - name: Ensure test package is installed
      package:
        name: tree
        state: present

    - name: Place role-specific marker
      copy:
        dest: /root/baseline-role-ran.txt
        content: |
          Baseline role ran on {{ inventory_hostname }}
          IP={{ ansible_default_ipv4.address | default('UNKNOWN') }}
          Satellite host={{ sat_host_fqdn }}
          provision_source={{ provision_source | default('UNDEFINED') }}
