---
- name: Post-register baseline (ISO-aware, IP-based)
  hosts: all
  gather_facts: yes

  # These are the Satellite API credentials the playbook will use
  # You can later move them to a credential / vars file.
  vars:
    satellite_url: "https://satellite.lab.example.com"
    satellite_api_user: "admin"      # dummy username - change in production
    satellite_api_password: "redhat" # dummy password - change in production

  tasks:
    - name: Show basic context as we see it from AAP
      debug:
        msg:
          target_ip: "{{ target_ip | default('UNDEFINED') }}"
          target_name: "{{ target_name | default('UNDEFINED') }}"
          inventory_hostname: "{{ inventory_hostname }}"
          ansible_ip: "{{ ansible_default_ipv4.address | default('NO_IP_FACT') }}"

    # ⚠ Hard filter: only the host whose IP matches target_ip continues.
    # All other inventory hosts (Satellite, Capsules, others) stop here.
    - name: Stop on all hosts except the one that just registered
      meta: end_host
      when: ansible_default_ipv4.address | default('') != target_ip | default('')

    # From this point on, only the new client continues.

    - name: Lookup Satellite host by IP
      uri:
        url: "{{ satellite_url }}/api/v2/hosts?search=ip={{ target_ip }}"
        method: GET
        user: "{{ satellite_api_user }}"
        password: "{{ satellite_api_password }}"
        force_basic_auth: yes
        validate_certs: no          # set to yes if your CA is trusted
        return_content: yes
      register: lookup_by_ip

    - name: Extract Satellite FQDN from lookup
      set_fact:
        sat_host_fqdn: >-
          {{
            (lookup_by_ip.json.results | default([]) | first).name
            | default('')
          }}

    - name: Fail clearly if Satellite could not find the host by IP
      fail:
        msg: >-
          Satellite API did not return a host for IP {{ target_ip }}.
          Raw response: {{ lookup_by_ip.json | default('NO JSON') }}
      when: sat_host_fqdn | length == 0

    - name: Show Satellite host FQDN we will use
      debug:
        msg:
          sat_host_fqdn: "{{ sat_host_fqdn }}"

    - name: Query Satellite API for host details
      uri:
        url: "{{ satellite_url }}/api/v2/hosts/{{ sat_host_fqdn }}"
        method: GET
        user: "{{ satellite_api_user }}"
        password: "{{ satellite_api_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: sat_host

    - name: Extract provision_source from host parameters
      set_fact:
        provision_source: >-
          {{
            (sat_host.json.all_parameters | default([]))
            | selectattr('name', 'eq', 'provision_source')
            | map(attribute='value')
            | first
            | default('')
          }}

    - name: Show provision_source value as seen from Satellite API
      debug:
        msg:
          provision_source: "{{ provision_source | default('UNDEFINED') }}"

    # If this is NOT an ISO host, end the play (for this host).
    - name: Skip everything if this is not an ISO host
      meta: end_play
      when: provision_source | default('') != 'iso'

    # From here down, only ISO hosts will run.

    - name: Inform that ISO baseline WILL run on this host
      debug:
        msg: >-
          ISO baseline WILL run on {{ inventory_hostname }}
          (IP={{ target_ip }}, provision_source={{ provision_source }})

    - name: Touch marker file to prove baseline ran
      file:
        path: /root/iso_baseline_ran
        state: touch

    - name: Ensure test package is installed
      package:
        name: tree
        state: present

    - name: Place role-specific marker
      copy:
        dest: /root/baseline-role-ran.txt
        content: |
          Baseline role ran on {{ inventory_hostname }}
          IP={{ target_ip | default('UNKNOWN') }}
          provision_source={{ provision_source | default('UNDEFINED') }}
