---
- name: Post-register baseline (ISO-aware, IP-based)
  hosts: "{{ target_name | default('all') }}"
  gather_facts: yes

  vars:
    satellite_url: "https://satellite.lab.example.com"
    # NOTE:
    #   satellite_api_token is injected by the AAP "Satellite API Token"
    #   credential type you created. Do NOT hardcode it here.

  tasks:

    - name: Show basic context as we see it from AAP
      debug:
        msg:
          inventory_hostname: "{{ inventory_hostname }}"
          target_name: "{{ target_name | default('UNDEFINED') }}"
          target_ip: "{{ target_ip | default('UNDEFINED') }}"
          ansible_ip: "{{ ansible_default_ipv4.address | default('UNKNOWN') }}"

    - name: Ensure target_ip is provided by webhook
      fail:
        msg: "target_ip from webhook is missing or empty; refusing to run."
      when: (target_ip | default('', true) | string | trim) | length == 0

    # ---- Look up the host in Satellite by IP ----

    - name: Lookup Satellite host by IP
      uri:
        url: "{{ satellite_url }}/api/v2/hosts?search=ip={{ target_ip | urlencode }}"
        method: GET
        headers:
          Authorization: "Bearer {{ satellite_api_token }}"
        validate_certs: no          # set to 'yes' when CA trust is configured
        return_content: yes
      register: lookup_by_ip

    - name: Fail clearly if Satellite could not find the host by IP
      fail:
        msg: >-
          Satellite did not return any hosts for ip={{ target_ip }}.
          Raw response: {{ lookup_by_ip.json }}
      when: (lookup_by_ip.json.results | default([]) | length) == 0

    - name: Set Satellite host FQDN
      set_fact:
        sat_host_fqdn: "{{ lookup_by_ip.json.results[0].name }}"

    - name: Show Satellite host FQDN we will use
      debug:
        msg:
          inventory_hostname: "{{ inventory_hostname }}"
          sat_host_fqdn: "{{ sat_host_fqdn }}"

    # ---- Pull host details from Satellite and read installation_source ----

    - name: Query Satellite API for host details
      uri:
        url: "{{ satellite_url }}/api/v2/hosts/{{ sat_host_fqdn }}"
        method: GET
        headers:
          Authorization: "Bearer {{ satellite_api_token }}"
        validate_certs: no
        return_content: yes
      register: sat_host

    - name: Extract installation_source from host parameters
      set_fact:
        installation_source: >-
          {{
            (sat_host.json.all_parameters | default([]))
            | selectattr('name', 'eq', 'installation_source')
            | map(attribute='value')
            | first
            | default('')
          }}

    - name: Show installation_source value as seen from Satellite API
      debug:
        msg:
          installation_source: "{{ installation_source | default('UNDEFINED') }}"

    - name: Skip everything if this is not an ISO host
      meta: end_play
      when: installation_source | default('') != 'iso'

    # ---- Actual baseline for ISO hosts ----

    - name: Inform that ISO baseline WILL run on this host
      debug:
        msg: "ISO baseline WILL run on {{ inventory_hostname }} (IP={{ target_ip }}, installation_source={{ installation_source }})"

    - name: Touch marker file to prove baseline ran
      file:
        path: /root/iso_baseline_ran
        state: touch

    - name: Ensure test package is installed
      package:
        name: tree
        state: present

    - name: Place role-specific marker
      copy:
        dest: /root/baseline-role-ran.txt
        content: |
          Baseline role ran on {{ inventory_hostname }}
          IP={{ target_ip }}
          installation_source={{ installation_source | default('UNDEFINED') }}
