---
- name: Post-register baseline (ISO-aware, IP-based)
  hosts: "{{ target_name | default('all') }}"
  gather_facts: yes

  vars:
    satellite_url: "https://satellite.lab.example.com"
    satellite_api_user: "admin"         # adjust
    satellite_api_password: "redhat"    # adjust or use a token/credential

  tasks:
    - name: Show basic context as we see it from AAP
      debug:
        msg:
          target_ip: "{{ target_ip | default('UNDEFINED') }}"
          target_name: "{{ target_name | default('UNDEFINED') }}"
          inventory_hostname: "{{ inventory_hostname }}"
          ansible_ip: "{{ ansible_default_ipv4.address | default('NO_IP_FACT') }}"

    - name: Fail early if target_ip is not defined
      fail:
        msg: "target_ip extra_var is required but not set — check the Satellite webhook template."
      when: target_ip is not defined or target_ip | string | length == 0

    - name: Sanity check that this host IP matches the target_ip from the webhook
      fail:
        msg: >-
          This host ({{ inventory_hostname }}) has IP {{ ansible_default_ipv4.address | default('NO_IP_FACT') }},
          but the webhook says target_ip={{ target_ip }}. Aborting to avoid touching the wrong host.
      when: ansible_default_ipv4.address | default('') != target_ip | string

    # -----------------------------
    # Talk to Satellite by IP
    # -----------------------------
    - name: Lookup Satellite host by IP
      uri:
        url: "{{ satellite_url }}/api/v2/hosts?search=ip={{ target_ip }}"
        method: GET
        user: "{{ satellite_api_user }}"
        password: "{{ satellite_api_password }}"
        force_basic_auth: yes
        validate_certs: no          # set to yes if you have proper CA trust
        return_content: yes
      register: lookup_by_ip
      run_once: false               # 1 host anyway, but explicit

    - name: Extract Satellite FQDN from lookup
      set_fact:
        sat_host_fqdn: "{{ (lookup_by_ip.json.results | default([]))[0].name | default('') }}"

    - name: Fail clearly if Satellite could not find the host by IP
      fail:
        msg: >-
          Satellite API did not return any host for IP={{ target_ip }}.
          Raw results: {{ lookup_by_ip.json.results | default([]) }}
      when: lookup_by_ip.json.results | default([]) | length == 0

    - name: Show Satellite host FQDN we will use
      debug:
        msg:
          sat_host_fqdn: "{{ sat_host_fqdn }}"
          inventory_hostname: "{{ inventory_hostname }}"

    # -----------------------------
    # Get parameters from Satellite
    # -----------------------------
    - name: Query Satellite API for host details
      uri:
        url: "{{ satellite_url }}/api/v2/hosts/{{ sat_host_fqdn }}"
        method: GET
        user: "{{ satellite_api_user }}"
        password: "{{ satellite_api_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: sat_host

    - name: Extract provision_source from host parameters
      set_fact:
        provision_source: >-
          {{
            (sat_host.json.all_parameters | default([]))
            | selectattr('name', 'eq', 'provision_source')
            | map(attribute='value')
            | first
            | default('')
          }}

    - name: Show provision_source value as seen from Satellite API
      debug:
        msg:
          provision_source: "{{ provision_source | default('UNDEFINED') }}"

    - name: Skip everything if this is not an ISO host
      meta: end_play
      when: provision_source | default('') != 'iso'

    # -----------------------------
    # Actual baseline work
    # -----------------------------
    - name: Inform that ISO baseline WILL run on this host
      debug:
        msg: >-
          ISO baseline WILL run on {{ inventory_hostname }}
          (IP={{ target_ip }}, provision_source={{ provision_source }})

    - name: Touch marker file to prove baseline ran
      file:
        path: /root/iso_baseline_ran
        state: touch

    - name: Ensure test package is installed
      package:
        name: tree
        state: present

    - name: Place role-specific marker
      copy:
        dest: /root/baseline-role-ran.txt
        content: |
          Baseline role ran on {{ inventory_hostname }}
          IP={{ target_ip }}
          provision_source={{ provision_source | default('UNDEFINED') }}
