- name: Post-register baseline (ISO-aware)
  hosts: all
  gather_facts: yes

  tasks:
    - name: Show provision_source value as seen by inventory
      debug:
        msg: "provision_source = {{ provision_source | default('UNDEFINED') }}"

    - name: Decide if this host should run ISO baseline
      set_fact:
        run_iso_baseline: "{{ provision_source | default('') == 'iso' }}"

    - name: Inform whether baseline will run
      debug:
        msg: >-
          ISO baseline {{ 'WILL' if run_iso_baseline else 'WILL NOT' }}
          run on {{ inventory_hostname }}

    - name: Touch marker file to prove baseline ran (ISO hosts only)
      file:
        path: /root/iso_baseline_ran
        state: touch
      when: run_iso_baseline

    - name: Ensure test package is installed (ISO hosts only)
      package:
        name: tree
        state: present
      when: run_iso_baseline

    - name: Place role-specific marker (ISO hosts only)
      copy:
        dest: /root/baseline-role-ran.txt
        content: "Baseline role ran on {{ inventory_hostname }} via ISO\n"
      when: run_iso_baseline
