---
- name: Post-register baseline (ISO-aware)
  hosts: all
  gather_facts: yes

  tasks:
    - name: Show provision_source value
      debug:
        msg: "provision_source = {{ provision_source | default('UNDEFINED') }}"

    - name: Skip everything if this is not an ISO host
      meta: end_play
      when: provision_source | default('') != 'iso'

    - name: Inform that ISO baseline WILL run on this host
      debug:
        msg: "ISO baseline WILL run on {{ inventory_hostname }} (provision_source={{ provision_source }})"

    - name: Touch marker file to prove baseline ran
      file:
        path: /root/iso_baseline_ran
        state: touch

    - name: Ensure test package is installed
      package:
        name: tree
        state: present
