---
- name: Post-register baseline (ISO-aware, IP-based)
  hosts: "{{ target_name | default('all') }}"
  gather_facts: yes

  tasks:

    - name: Show basic context as we see it from AAP
      debug:
        msg:
          inventory_hostname: "{{ inventory_hostname }}"
          target_name: "{{ target_name | default('UNDEFINED') }}"
          target_ip: "{{ target_ip | default('UNDEFINED') }}"
          ansible_ip: "{{ ansible_default_ipv4.address | default('UNKNOWN') }}"
          satellite_url: "{{ satellite_url }}"
          satellite_api_user: "{{ satellite_api_user }}"

    - name: Ensure target_ip is provided by webhook
      fail:
        msg: "target_ip from webhook is missing or empty; refusing to run."
      when: (target_ip | default('', true) | string | trim) | length == 0


    # ---- Look up the host in Satellite by IP ----

    - name: Lookup Satellite host by IP
      uri:
        url: "{{ satellite_url }}/api/v2/hosts?search=ip={{ target_ip | urlencode }}"
        method: GET
        user: "{{ satellite_api_user }}"
        password: "{{ satellite_api_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: lookup_by_ip

    - name: Fail clearly if Satellite could not find the host by IP
      fail:
        msg: >-
          Satellite did not return any hosts for ip={{ target_ip }}.
          Raw response: {{ lookup_by_ip.json }}
      when: (lookup_by_ip.json.results | default([]) | length) == 0

    - name: Set Satellite host FQDN
      set_fact:
        sat_host_fqdn: "{{ lookup_by_ip.json.results[0].name }}"

    - name: Show Satellite host FQDN
      debug:
        msg:
          sat_host_fqdn: "{{ sat_host_fqdn }}"


    # ---- Query Satellite for details ----

    - name: Query Satellite API for host details
      uri:
        url: "{{ satellite_url }}/api/v2/hosts/{{ sat_host_fqdn }}"
        method: GET
        user: "{{ satellite_api_user }}"
        password: "{{ satellite_api_password }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: sat_host

    - name: Extract installation_source from host parameters
      set_fact:
        installation_source: >-
          {{
            (sat_host.json.all_parameters | default([]))
            | selectattr('name', 'eq', 'installation_source')
            | map(attribute='value')
            | first
            | default('')
          }}

    - name: Show installation_source value
      debug:
        msg:
          installation_source: "{{ installation_source }}"


    # ---- Conditional execution ----

    - name: Skip if not ISO
      meta: end_play
      when: installation_source != "iso"


    # ---- Run ISO baseline ----

    - name: Touch marker file
      file:
        path: /root/iso_baseline_ran
        state: touch

    - name: Ensure tree installed
      package:
        name: tree
        state: present

    - name: Create role marker
      copy:
        dest: /root/baseline-role-ran.txt
        content: |
          Baseline role ran on {{ inventory_hostname }}
          IP={{ target_ip }}
          installation_source={{ installation_source }}
